// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6NLWudErdS36GAiQV75xrZV5rNwBlx8',
    appId: '1:768999817001:web:4a06218e2637351d450138',
    messagingSenderId: '768999817001',
    projectId: 'talabat-8d4c1',
    authDomain: 'talabat-8d4c1.firebaseapp.com',
    storageBucket: 'talabat-8d4c1.firebasestorage.app',
    measurementId: 'G-3DKQ9LCZTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJPIoIRvxgVzwA4p6yBllwsk5Im826gc',
    appId: '1:768999817001:android:dc20855941793465450138',
    messagingSenderId: '768999817001',
    projectId: 'talabat-8d4c1',
    storageBucket: 'talabat-8d4c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjf6l8NoH2l6CSt_MVAEMtIB9JI7uqqU',
    appId: '1:768999817001:ios:ff8f9fbf298cea34450138',
    messagingSenderId: '768999817001',
    projectId: 'talabat-8d4c1',
    storageBucket: 'talabat-8d4c1.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjf6l8NoH2l6CSt_MVAEMtIB9JI7uqqU',
    appId: '1:768999817001:ios:ff8f9fbf298cea34450138',
    messagingSenderId: '768999817001',
    projectId: 'talabat-8d4c1',
    storageBucket: 'talabat-8d4c1.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6NLWudErdS36GAiQV75xrZV5rNwBlx8',
    appId: '1:768999817001:web:760303bc1d1c68af450138',
    messagingSenderId: '768999817001',
    projectId: 'talabat-8d4c1',
    authDomain: 'talabat-8d4c1.firebaseapp.com',
    storageBucket: 'talabat-8d4c1.firebasestorage.app',
    measurementId: 'G-7P6S04NPB7',
  );
}
